### ISSUE TITLE
Extend DragDropContext to accept a window parameter

### ISSUE THREAD

**Issue by danbaechtold** [jenshaase/vue-react-dnd#2]
Hi,

First of all, thanks a lot for this awesome package, and the really helpful "Frame" example!

I needed to extend DragDropContext to accept a window parameter, too, similar to DragDropContextProvider does. Here is my code how I made it work for our use case:

```
import { DragDropManager } from 'dnd-core'

export default function DragDropContext (backendOrModule, window) {
  let backend = backendOrModule
  if (typeof backend === 'object' && typeof backend.default === 'function') {
    backend = backend.default
  }

  return {
    provide: {
      dragDropManager: new DragDropManager(backend, {
        window: window
      })
    }
  }
}
```

Could that be added to your code?

A few small other things I've learned/discovered:
- When reading your Readme, it wasn't clear to me that not both DragDropContext  and DragDropContextProvider have to be used, but only one of them. Of course this get's clear when reading the React-DnD doc, but it would be nice to say it here, too
- Imports only work when ../src/.. is added to the path
- DragDropContextProvider.vue has 'App' as name. This should be renamed to 'DragDropContextProvider'

Thank you,
Dan

**Comment by jenshaase** [comment]
Hi,

thanks for your Feedback. I just published a new version that should fix the problem. However, instead of providing a the window as second parameter you need to provide a context object.

For your use case it should work like this:
`DragDropContext(HTML5Backend, { window: myWindow } )`

I also fixed the other issues:
- Imports work now without 'src'. (I updated the Readme for examples)
- DragDropContextProvider has now the correct name

Best regards,
Jens

**Comment by danbaechtold** [comment]
Awesome, thanks!!
